[book]
title        = "ESP32-C3 Wireless Adventure: A Comprehensive Guide to IoT"
authors      = ["Espressif Systems"]
description  = "A comprehensive guide to IoT"
language     = "en"
src = "src"

[output.html]
git-repository-url = "https://github.com/espressif/esp32-c3-book-en/"
mathjax-support = true
edit-url-template = "https://github.com/espressif/esp32-c3-book-en/blob/main/WRITINGS.md"
